{
 "title": "Franchise Pipeline Monitoring PROD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stage",
    "query": {
     "query": "select distinct lower(stage) from data_quality_ledger"
    }
   }
  ]
 },
 "panels": [
  { "title": "Great Expectations Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate by Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "gx_metadata",
     "rawSql": "SELECT\n    execution_date AS time,\n    lower(stage),\n    AVG(success_rate) AS success_rate\nFROM data_quality_ledger\nGROUP BY execution_date, stage\nORDER BY execution_date;"
    }
   ]
  },
  {
   "title": "Validated Data Volume by Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "dataset": "gx_metadata",
     "rawSql": "WITH asset_daily_volume AS (\n    SELECT\n        execution_date,\n        stage,\n        asset_name,\n        MAX(volume) AS volume\n    FROM data_quality_ledger\n    GROUP BY execution_date, stage, asset_name\n)\nSELECT\n    execution_date::timestamp AS time,\n    stage AS metric, -- Kolom ini yang otomatis bikin garisnya terpisah (Bronze, Silver, Gold, dll)\n    SUM(volume) AS value\nFROM asset_daily_volume\nGROUP BY execution_date, stage\nORDER BY execution_date;\n"
    }
   ]
  },
  {
   "title": "Failed Validations by Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "gx_metadata",
     "rawSql": "SELECT\n    execution_date::timestamp AS time,\n    stage AS metric,\n    COUNT(*) FILTER (WHERE status = 'FAILED') AS value\nFROM data_quality_ledger\nGROUP BY execution_date, stage\nORDER BY execution_date;"
    }
   ]
  },
  {
   "title": "Validation Runs by Stage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "dataset": "gx_metadata",
     "rawSql": "SELECT\n    date_trunc('day', created_at) AS time,\n    stage AS metric,\n    COUNT(*) AS value\nFROM data_quality_ledger\nGROUP BY 1, stage\nORDER BY 1;"
    }
   ]
  }
 ]
}